spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/exercise_base_01?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(EwHMQ5z/q1oVkK8y0nJEHQ==)

#  session:
##    关闭session
#    store-type: none



server:
  port: 8060


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.company.model

#security:
#  basic:
#    关闭security
#    enabled: false

#cp.security.browser.loginPage: /demo-signIn.html
#cp.security.browser.loginType: REDIRECT


#应用级配置
cp.security.code.image.length: 6
cp.security.code.image.width: 100
cp.security.code.image.url: /user,/user/*

cp.security.browser.signUpUrl: /demo-signUp.html
